### ISSUE TITLE
Bad performance while idle

### ISSUE THREAD

**Issue by bdcomp** [james-fray/tab-reloader#3] opened 2016-06-03 06:17 UTC
Using the just released about:performance I discovered that Tab Reloader is slowing down my Firefox while idle:
Impact on framerate: 4/10 - 7/10
CPU usage: 10% - 59% (!)
System usage: 1% - 2%

Tab Reloader 0.1.2
Firefox 47
Kubuntu 16.04 64bit

**Comment by bdcomp** [comment] 2016-06-03 09:58
Additional info (clearing the "Display only the latest 10s"):
"Tab Reloader seems to have slown down Firefox very often. When this happens, the slowdown is generally noticeable"
Impact on framerate: 0 high-impacts, 156 medium-impact.
CPU usage: 2% (total 2824114ms).
System usage: 1% (total 264738ms).
Blocking process calls: 0% (total 0ms).

**Comment by james-fray** [comment] 2016-06-08 05:32
This is what I got with one active job:
![screen shot 2016-06-08 at 10 00 20](https://cloud.githubusercontent.com/assets/9897733/15883716/07e3e74e-2d60-11e6-8eb1-0c6c99a796c0.png)

Can you try the extension on a clean profile? http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by bdcomp** [comment] 2016-06-08 05:42
Thanks for your reply.

Our results is very different - may I ask you to check it with several tabs?

In fact, with several tabs, it starts to slowing down after less than a minute!

**Comment by james-fray** [comment] 2016-06-08 07:36
I see. Please try the latest dev version
https://github.com/james-fray/tab-reloader/blob/master/builds/packed/firefox.xpi?raw=true

Still when a new tab is opened, "about:performance" displays 1% CPU usage (noting like 10% that you have reported. I have about 100 open tabs). But it goes back to zero after a few seconds. I am still not sure why opening a new tab causes CPU usage. Tab Reloader just checks the toolbar status when a new tab is added or removed. This operation should not consume 1% of CPU. I suspect this is an internal SDK issue. Will do more investigations. Let me know how the dev version performs for you

**Comment by bdcomp** [comment] 2016-06-08 08:08
Dev version, idle, about 23 tabs:
Tab Reloader seems to have slown down Firefox very often. When this happens, the slowdown is generally noticeable.
Full name: jid0-bnmfwWw2w2w4e4edvcdDbnMhdVg@jetpack.
Impact on framerate: 0 high-impacts, 136 medium-impact.
CPU usage: 7% (total 4206538ms).
System usage: 1% (total 267125ms).
Blocking process calls: 0% (total 0ms).
Measure start: 709 seconds ago.
Processes: 3485 (parent)

**Comment by bdcomp** [comment] 2016-06-08 08:12
Release version: 1 medium-impact per 7 seconds
Dev version: 1 medium-impact per 5.2 seconds

**Comment by james-fray** [comment] 2016-06-08 10:03
> Dev version: 1 medium-impact per 5.2 seconds

Where did you get this info from?

Okay so I prepared a minimal SDK based addon that only loads a button and a panel. Each time you open or close a tab, it prints the tab's id in the console. That's it. This extension does not use anything fancy. So it basically should have no effect on Firefox performance. Please give it a try and see how it performs. I do recommend to try it in both current profile and a new one.

[test.zip](https://github.com/james-fray/tab-reloader/files/304460/test.zip)
Extract and use *.XPI. The rest is the actual code.

**Comment by bdcomp** [comment] 2016-06-08 10:13
> Dev version: 1 medium-impact per 5.2 seconds
Where did you get this info from?

709/136=5.2
The numbers is from dev version data, my previous comment.

**Comment by bdcomp** [comment] 2016-06-08 15:54
Full name: @test.
Impact on framerate: 0 high-impacts, 121 medium-impact (3 alerts).
CPU usage: 6% (total 3980818ms).
System usage: 1% (total 139611ms).
Blocking process calls: 0% (total 0ms).
Measure start: 699 seconds ago.
Processes: 3485 (parent)

Please open a bug against the SDK/Jetpack.

**Comment by bdcomp** [comment] 2016-06-12 20:40
@james-fray Any news?

**Comment by cluclead** [comment] 2016-06-20 05:16
I am not able to reproduce this high CPU usage. Can you try the test XPI on another system as well?

**Comment by cluclead** [comment] 2016-06-20 05:17
@james-fray I am on a Mac PC

**Comment by bdcomp** [comment] 2016-06-20 05:28
@cluclead The CPU usage is probably system speed dependent.
How about "Impact on framerate" - any noted?

Although I not tried the test XPI beside my main Linux system, the release add-on is slowing down also a Windows 7 system I worked on.

I still think it should be investigated on the SDK/Jetpack level.

**Comment by cluclead** [comment] 2016-06-20 06:12
> How about "Impact on framerate" - any noted?

about 3/10.

**Comment by cluclead** [comment] 2016-06-20 06:15
@bdcomp please share your results of the test XPI with https://groups.google.com/forum/#!forum/mozilla-labs-jetpack

**Comment by bdcomp** [comment] 2016-07-06 15:37
Jetpack discussion: https://groups.google.com/forum/#!topic/mozilla-labs-jetpack/ZTIFn6wffS4

**Comment by james-fray** [comment] 2017-11-23 13:02
This has been fixed by WebEx release!

**Closed by james-fray** 2017-11-23 13:03 UTC
